# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2

updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 1
    directory: '/'
    schedule:
      day: 'sunday'
      interval: 'weekly'
    groups:
      github-actions:
        patterns: ['*']

  - package-ecosystem: 'gomod'
    open-pull-requests-limit: 1
    directory: '/'
    schedule:
      day: 'sunday'
      interval: 'weekly'
    groups:
      gomod-security:
        applies-to: security-updates
        update-types: ['minor', 'patch']
        patterns: ['*']
      gomod-update:
        applies-to: version-updates
        update-types: ['minor', 'patch']
        patterns: ['*']
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: docker
    open-pull-requests-limit: 1
    directory: '/build'
    schedule:
      day: 'sunday'
      interval: 'weekly'
    groups:
      docker-security:
        applies-to: security-updates
        update-types: ['minor', 'patch']
        patterns: ['*']
      docker-update:
        applies-to: version-updates
        update-types: ['minor', 'patch']
        patterns: ['*']
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
