project_name: contentserver

release:
  github:
    owner: foomo
    name: contentserver
  prerelease: auto

builds:
  - binary: contentserver
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    env:
      - CGO_ENABLED=0
    main: ./main.go
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/foomo/contentserver/cmd.version={{.Version}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

changelog:
  use: github-native

brews:
  # Repository to push the tap to.
  - repository:
      owner: foomo
      name: homebrew-tap
    caveats: "sesamy --help"
    homepage: "https://github.com/foomo/contentserver"
    description: "Serves content tree structures very quickly"
    test: |
      system "#{bin}/contentserver --version"

docker_manifests:
  # basic
  - name_template: 'foomo/contentserver:latest'
    image_templates:
      - 'foomo/contentserver:{{ .Tag }}-amd64'
      - 'foomo/contentserver:{{ .Tag }}-arm64'

  - name_template: 'foomo/contentserver:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - 'foomo/contentserver:v{{ .Major }}.{{ .Minor }}-amd64'
      - 'foomo/contentserver:v{{ .Major }}.{{ .Minor }}-arm64'

  - name_template: 'foomo/contentserver:{{ .Tag }}'
    image_templates:
      - 'foomo/contentserver:{{ .Tag }}-amd64'
      - 'foomo/contentserver:{{ .Tag }}-arm64'

  # alpine
  - name_template: 'foomo/contentserver:latest-alpine'
    image_templates:
      - 'foomo/contentserver:{{ .Tag }}-alpine-amd64'
      - 'foomo/contentserver:{{ .Tag }}-alpine-arm64'

  - name_template: 'foomo/contentserver:v{{ .Major }}.{{ .Minor }}-alpine'
    image_templates:
      - 'foomo/contentserver:v{{ .Major }}.{{ .Minor }}-alpine-amd64'
      - 'foomo/contentserver:v{{ .Major }}.{{ .Minor }}-alpine-arm64'

  - name_template: 'foomo/contentserver:{{ .Tag }}-alpine'
    image_templates:
      - 'foomo/contentserver:{{ .Tag }}-alpine-amd64'
      - 'foomo/contentserver:{{ .Tag }}-alpine-arm64'
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: build/buildx.Dockerfile
    image_templates:
      - 'foomo/contentserver:latest-amd64'
      - 'foomo/contentserver:{{ .Tag }}-amd64'
      - 'foomo/contentserver:v{{ .Major }}.{{ .Minor }}-amd64'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Serves content tree structures very quickly'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation={{.GitURL}}'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/amd64'

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: build/buildx.Dockerfile
    image_templates:
      - 'foomo/contentserver:latest-arm64'
      - 'foomo/contentserver:{{ .Tag }}-arm64'
      - 'foomo/contentserver:v{{ .Major }}.{{ .Minor }}-arm64'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Serves content tree structures very quickly'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation={{.GitURL}}'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/arm64'

  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: build/buildx-alpine.Dockerfile
    image_templates:
      - 'foomo/contentserver:latest-alpine-amd64'
      - 'foomo/contentserver:{{ .Tag }}-alpine-amd64'
      - 'foomo/contentserver:v{{ .Major }}.{{ .Minor }}-alpine-amd64'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Serves content tree structures very quickly'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation={{.GitURL}}'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/amd64'

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: build/buildx-alpine.Dockerfile
    image_templates:
      - 'foomo/contentserver:latest-alpine-arm64'
      - 'foomo/contentserver:{{ .Tag }}-alpine-arm64'
      - 'foomo/contentserver:v{{ .Major }}.{{ .Minor }}-alpine-arm64'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Serves content tree structures very quickly'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation={{.GitURL}}'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/arm64'
