name: Release Tag

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unshallow
        run: git fetch --prune --unshallow

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - id: app_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}

      - name: Login to docker.io
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --timeout=90m
        env:
          GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
